### ISSUE TITLE
Fancy updates from data to project

### ISSUE THREAD

**Issue by critmcdonald** [statesman/single-page-project#21]
Once we have an easy Google based content, we want to be able to get content updated in a number of ways beyond the developer firing it off at the command-line. We talked about this being the finished baked files like in [JSON to HMLT](#20), but it may also be moving just a JSON file?

Among the fancy methods:
- [ ] on a chron, possibly with custom interval
- [ ] on demand through a web interface accessible in the newsroom
- [ ] remotely through Slack
